### ISSUE TITLE
Update boto3 dependency to py311-boto3 for OPNsense 24

### ISSUE THREAD

**Issue by studioph** [threatpatrols/opnsense-plugin-configsync#6]
It looks like the `py39` package collection is no longer present in 24.1, superseded by the `py311` collection. Would it be possible to update the boto3 dependency to `py311-boto3`? I would be happy to make a PR for this, but I don't see the dependency listed anywhere in this repo, only appearing in the `packagesite.yaml` on `repo.threatpatrols.com`, which leads me to believe it's something only you can update.

Appreciate all the work you've put into this!

**Comment by ndejong** [comment]
Hi @studioph have taken a look into this for you 

Yes, this one got away from us as we did not notice the mid-cycle Python upgrade in 24.1 from Py39 to Py311 - totally our fault.

We've got a release builder with the latest 24.1 that includes py311 just now and the `configsync` update should be ready in a few hours.

To your note that there is no mention of `boto3` in the package (ie in the Makefile) this is because we inject this value in the build process to accommodate python prefix changes such as in this case from `py39-` to `py311-`

Here's a lovely view of our internal build instances as we play catchup

![image](https://github.com/threatpatrols/opnsense-plugin-configsync/assets/210474/cf2c73ac-ef69-4350-a9d1-a1b2a8c2e842)

**Comment by ndejong** [comment]
[os-configsync-0.4.35.pkg](https://repo.threatpatrols.com/opnsense/FreeBSD%3A13%3Aamd64/24.1/stable/All/os-configsync-0.4.35.pkg) released to 24.1 stable branch, that resolves this issue.

A regular OPNsense update should make the 0.4.35 version available to install and/or upgrade.

Thanks for reporting.

**Comment by studioph** [comment]
Thank you for the update Nicholas!
